// Fleet ship data with placeholder model paths
export const fleetShips = [
  {
    id: 'idris',
    name: 'Aegis Idris-P',
    manufacturer: 'Aegis Dynamics',
    class: 'Capital Corvette',
    role: 'Command & Control',
    crew: '10-12',
    length: '236m',
    mass: '3,700,000 kg',
    cargo: '228 SCU',
    topSpeed: '155 m/s',
    description: 'The crown jewel of the fleet. A fully militarized corvette capable of deploying fighters and serving as a mobile command center.',
    modelPath: '/models/ships/idris.glb',
    thumbnail: '/backgrounds/SC-3.19_20230524_130313_Fleet-selfie_ILW2953_f.png',
    meshType: 'capital',
    accentColor: '#10b981',
    weapons: '8× S4, 4× S5, 1× S10',
    features: ['Command Bridge', 'Fighter Bay', 'Medbay', 'Armory', 'Brig'],
    specs: {
      shields: { label: 'Shield Class', value: 'Capital', pct: 95 },
      armor: { label: 'Armor Rating', value: 'Heavy', pct: 90 },
      firepower: { label: 'Firepower', value: 'Extreme', pct: 98 },
      speed: { label: 'Agility', value: 'Low', pct: 20 },
      stealth: { label: 'Stealth', value: 'Minimal', pct: 8 },
    },
  },
  {
    id: 'f8c',
    name: 'Anvil F8C Lightning',
    manufacturer: 'Anvil Aerospace',
    class: 'Heavy Fighter',
    role: 'Space Superiority',
    crew: '1',
    length: '22m',
    mass: '28,000 kg',
    cargo: '3 SCU',
    topSpeed: '280 m/s',
    description: 'Elite dogfighter designed for absolute air superiority. Unmatched agility and devastating forward firepower.',
    modelPath: '/models/ships/f8c.glb',
    thumbnail: '/backgrounds/SC-3.24_20241207_170744_Hornets-Over-Lake_f.png',
    meshType: 'fighter',
    accentColor: '#ff3366',
    weapons: '4× S3, 2× S4',
    features: ['Ejection Seat', 'Advanced Avionics', 'Stealth Coating', 'Afterburner'],
    specs: {
      shields: { label: 'Shield Class', value: 'Medium', pct: 55 },
      armor: { label: 'Armor Rating', value: 'Medium', pct: 50 },
      firepower: { label: 'Firepower', value: 'High', pct: 75 },
      speed: { label: 'Agility', value: 'Extreme', pct: 95 },
      stealth: { label: 'Stealth', value: 'Low', pct: 35 },
    },
  },
  {
    id: 'aquila',
    name: 'RSI Constellation Aquila',
    manufacturer: 'Roberts Space Industries',
    class: 'Multi-Role Explorer',
    role: 'Deep Space Exploration',
    crew: '4-5',
    length: '61m',
    mass: '190,000 kg',
    cargo: '96 SCU',
    topSpeed: '150 m/s',
    description: 'Long-range exploration vessel with advanced scanning arrays and a snub fighter bay for planetary recon.',
    modelPath: '/models/ships/aquila.glb',
    thumbnail: '/backgrounds/9a5b333b-3981-4d6a-a235-7e91fc1c6ff8.jpg',
    meshType: 'explorer',
    accentColor: '#ffaa00',
    weapons: '4× S2, 2× S4, P-52 Merlin',
    features: ['Cartography Suite', 'Rover Bay', 'Snub Fighter', 'Long Range Scanners'],
    specs: {
      shields: { label: 'Shield Class', value: 'Large', pct: 70 },
      armor: { label: 'Armor Rating', value: 'Medium', pct: 55 },
      firepower: { label: 'Firepower', value: 'Moderate', pct: 50 },
      speed: { label: 'Agility', value: 'Medium', pct: 45 },
      stealth: { label: 'Stealth', value: 'Medium', pct: 50 },
    },
  },
  {
    id: 'cutlass',
    name: 'Drake Cutlass Black',
    manufacturer: 'Drake Interplanetary',
    class: 'Medium Freighter',
    role: 'Multi-Role / Cargo',
    crew: '2-3',
    length: '50m',
    mass: '88,000 kg',
    cargo: '48 SCU',
    topSpeed: '180 m/s',
    description: 'The workhorse. Versatile, rugged, and surprisingly agile for its size. Perfect for cargo runs in contested space.',
    modelPath: '/models/ships/cutlass.glb',
    thumbnail: '/backgrounds/SC-3.19_20230524_130313_Fleet-selfie_ILW2953_f.png',
    meshType: 'medium',
    accentColor: '#44ff88',
    weapons: '4× S2, 2× S3',
    features: ['Rear Ramp', 'Tractor Beam', 'Side Turret', 'Modular Cargo'],
    specs: {
      shields: { label: 'Shield Class', value: 'Medium', pct: 50 },
      armor: { label: 'Armor Rating', value: 'Medium', pct: 55 },
      firepower: { label: 'Firepower', value: 'Moderate', pct: 45 },
      speed: { label: 'Agility', value: 'High', pct: 70 },
      stealth: { label: 'Stealth', value: 'Medium', pct: 40 },
    },
  },
  {
    id: 'reclaimer',
    name: 'Aegis Reclaimer',
    manufacturer: 'Aegis Dynamics',
    class: 'Industrial Capital',
    role: 'Salvage Operations',
    crew: '5-8',
    length: '155m',
    mass: '2,800,000 kg',
    cargo: '3680 SCU',
    topSpeed: '110 m/s',
    description: 'The ultimate salvage platform. Massive industrial arms strip derelicts clean while the crew processes materials onboard.',
    modelPath: '/models/ships/reclaimer.glb',
    thumbnail: '/backgrounds/SC-3.24_20241207_170744_Hornets-Over-Lake_f.png',
    meshType: 'industrial',
    accentColor: '#ff8800',
    weapons: '2× S5 Turrets',
    features: ['Salvage Arms', 'Processing Plant', 'Drone Bay', 'Crew Quarters', 'Cargo Hold'],
    specs: {
      shields: { label: 'Shield Class', value: 'Capital', pct: 80 },
      armor: { label: 'Armor Rating', value: 'Heavy', pct: 85 },
      firepower: { label: 'Firepower', value: 'Low', pct: 20 },
      speed: { label: 'Agility', value: 'Very Low', pct: 10 },
      stealth: { label: 'Stealth', value: 'None', pct: 5 },
    },
  },
  {
    id: '600i',
    name: 'Origin 600i Explorer',
    manufacturer: 'Origin Jumpworks',
    class: 'Luxury Explorer',
    role: 'Luxury / Exploration',
    crew: '3-5',
    length: '91m',
    mass: '420,000 kg',
    cargo: '40 SCU',
    topSpeed: '195 m/s',
    description: 'Where performance meets opulence. The 600i features a revolutionary bridge and unmatched luxury for deep-space journeys.',
    modelPath: '/models/ships/600i.glb',
    thumbnail: '/backgrounds/9a5b333b-3981-4d6a-a235-7e91fc1c6ff8.jpg',
    meshType: 'luxury',
    accentColor: '#aa88ff',
    weapons: '3× S3, 2× S5 Turrets',
    features: ['Panoramic Bridge', 'VIP Quarters', 'Bar & Lounge', 'Scanning Suite'],
    specs: {
      shields: { label: 'Shield Class', value: 'Large', pct: 72 },
      armor: { label: 'Armor Rating', value: 'Medium', pct: 60 },
      firepower: { label: 'Firepower', value: 'Moderate', pct: 55 },
      speed: { label: 'Agility', value: 'Medium', pct: 50 },
      stealth: { label: 'Stealth', value: 'Low', pct: 30 },
    },
  },
];
